name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        uses: anthropics/claude-code-action@v1-dev
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Review this PR. Be brief and direct.

            List only actual concerns or bugs found.
            No recommendations, impact analysis, or general observations.
            Skip if already reviewed or no issues found.

            Use `gh pr comment:*` for comments.
            Use `mcp__github_inline_comment__create_inline_comment` for specific code issues.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*), Bash(gh pr diff:*), Bash(gh pr view:*)"